### PR TITLE
Rewritten following Python conventions and with better libraries

### PR DESCRIPTION
**Pull request by k4yt3x**
- Added shebang and metadata doc block on top of every Python file.
- Rewritten FFmpeg handler and upscaler using `pathlib.Path` objects instead of strings.
- Rewritten FFmpeg handler with `python-ffmpeg`.
- Changed variable and function names to PEP8-recommended Python-styled lowercase, underscore-separated names.
- Added more inline comments.
- Updated documentations in README.md for the changes made.

### CODE REVIEW

**Comment by k4yt3x** [comment]
I haven't tested the changes yet since I'm not sure how this thing can be compiled with the underlying CPP files and headers.

**Comment by TianZerL** [comment]
I will merge it first and test it later.

**Comment by TianZerL** [comment]
Well, I just completely refactored the low level api, now pyanime4k almost support all feature of anime4kcpp core, and it is more easy to install now(just copy the dll from Anime4KCPP to the right place).  
Looks like you used the wrong FFmpeg lib of python, you code shows you are using `ffmpeg-python` not `python-ffmpeg`.

**Comment by k4yt3x** [comment]
I'm using the right library, but wrote the wrong name in the documentation.
I intended to use `ffmpeg-python`.

**Comment by k4yt3x** [comment]
Maybe provide a documentation for how to install this.

**Comment by TianZerL** [comment]
This what am i doing now.

**Comment by TianZerL** [comment]
Done, please check it out. other OS may test in tomorrow.

**Comment by k4yt3x** [comment]
I see a number of issues in the newly updated code. Some are formatting and conventional issues, and some are logical errors or typos. Here's one for example:

image

1. Placeholders in strings isn't the most elegant solution anymore. Try using format strings or f-strings.
1. There's only one placeholder, but two arguments.
1. I think you tried to say `self.msg`.

I can fix these issues when I find time if you give me a collaborator on this project. Making forks and creating PRs is too time-consuming and I currently don't have the extra time for it.

**Comment by TianZerL** [comment]
Sure, I'd like to invite to be the collaborator. I only tested the general features in the newest code, not the details.

**Pull request merged**
